Kk startupjs task1
KondrashovKonstantin/stellar pull request #2
Opened 2020-12-09 18:19 UTC by KondrashovKonstantin

2020-12-10 11:15 UTC, veronicazh commented on main/pages/PHome/Header/index.styl
> +  line-height 3.5u
line-height только целый юнит, в данном случае 3u

2020-12-10 11:16 UTC, veronicazh commented on main/pages/PHome/Header/index.styl
> +  line-height 3.5u
целый юнит

2020-12-10 11:26 UTC, veronicazh commented on components/ContentTitle/index.styl
> +    line-height 5u
4u, 5 много

2020-12-10 11:29 UTC, veronicazh commented on components/PlainText/index.styl
> +    padding-top 3u
это должен быть margin, но мы не можем давать внешние отступы переиспользуемым компонентам. для этого есть врапперы на месте вызова

2020-12-10 11:38 UTC, veronicazh commented on components/ButtonG/index.styl
> +    margin-top 2u
мы не можем давать margin кнопке, которая используется в разных местах

2020-12-10 11:45 UTC, veronicazh commented on main/pages/PHome/MainContent/Cards/IconContent/index.styl
> +  margin-top 3u
нужно дать его .icon-wrapper (название неудачное, это просто .root), у первого аннулировать. а отступ от заголовка сделать в Cards за счет контейнера этих трех карточек

2020-12-10 11:46 UTC, veronicazh commented on main/pages/PHome/MainContent/Cards/IconContent/index.styl
> +  margin 3px
padding, так как это отступ от родительского элемента к дочернему

2020-12-10 11:47 UTC, veronicazh commented on main/pages/PHome/MainContent/Cards/IconContent/index.styl
> +  padding-top 3u
это margin

2020-12-10 11:49 UTC, veronicazh commented on main/pages/PHome/MainContent/Statistic/StatCard/index.styl
> +  height 23u
нельзя давать элементам фиксированную высоту без крайней необходимости

2020-12-10 11:50 UTC, veronicazh commented on main/pages/PHome/MainContent/Statistic/StatCard/index.styl
> +    padding 1u
замени на margin-top

2020-12-10 11:52 UTC, veronicazh commented on main/pages/PHome/Footer/index.js
> +    View.wrapper
такие элементы обычно всегда именуются .root

2020-12-10 11:53 UTC, veronicazh commented on main/pages/PHome/Footer/index.styl
> +    margin-top 4u
нужно убрать, а этот отступ сделать от рута

2020-12-10 11:54 UTC, veronicazh commented on main/pages/PHome/Footer/index.styl
> +        margin-top 2u
у первого нужно аннулировать (гайд, общие правила, п. 14)

2020-12-10 11:55 UTC, veronicazh commented on main/pages/PHome/Footer/index.styl
> +    margin-left -2u
лишнее

2020-12-10 11:56 UTC, veronicazh commented on main/pages/PHome/Footer/index.styl
> +        margin-left 2u
у первого нужно аннулировать

2020-12-10 11:56 UTC, veronicazh commented on main/pages/PHome/Footer/index.styl
> +    margin-bottom 3u
лишний

2020-12-10 11:57 UTC, veronicazh commented on main/pages/PHome/Footer/index.styl
> +    margin-top 2u
увеличь

2020-12-10 11:57 UTC, veronicazh commented on main/pages/PHome/Footer/index.styl
> +    margin-bottom 8u
убери этот margin, вместо этого дай паддинг боттом руту

2021-01-19 22:16 UTC, Arsen-Sultanov commented on main/pages/PHome/Footer/index.js
> +const tel = BASE_URL + 'telegram.png'
сделай массив `[ 'linkedin.png',  'github-logo.png', ...]`

2021-01-19 22:16 UTC, Arsen-Sultanov commented on main/pages/PHome/Footer/index.js
> +import { ButtonG } from '../../../../components'
у тебя есть алиас "components"
`import { ButtonG } from 'components'`

2021-01-19 22:16 UTC, Arsen-Sultanov commented on main/pages/PHome/Footer/index.js
> +        View.wrapp-chld
Что то с отступами

2021-01-19 22:16 UTC, Arsen-Sultanov commented on main/pages/PHome/Footer/index.js
> +                    Image.snicon(source={uri:lind})
Использу цикл, что бы вывести картинки из массива
https://pugjs.org/language/iteration.html

2021-01-19 22:16 UTC, Arsen-Sultanov commented on main/pages/PHome/Footer/index.js
> +const BASE_URL = 'http://localhost:3010/public/'
import { BASE_URL } from '@env'

2021-01-19 22:16 UTC, Arsen-Sultanov commented on main/pages/PHome/Footer/index.styl
> +        margin-left 2u
![Снимок экрана 2021-01-20 в 1 03 14](https://user-images.githubusercontent.com/20321278/105098610-61bb9680-5abb-11eb-8d50-c1d04da8dd79.png)
Добавь эти две строчки сюда что бы иконки были по центру `justify-content center align-items center`

2021-01-19 22:16 UTC, Arsen-Sultanov commented on main/pages/PHome/Footer/index.js
> +            View.btn-wrapper
![Снимок экрана 2021-01-20 в 1 08 13](https://user-images.githubusercontent.com/20321278/105099090-29688800-5abc-11eb-84bb-e5d300959484.png)
Текст не должен переносится (tablet)

2021-01-19 22:16 UTC, Arsen-Sultanov commented on main/pages/PHome/Footer/index.js
> +                    Text.contacts-wrapper__element(styleName='detailed') information@untitled.tld
Используй https://pugjs.org/language/iteration.html 
`[{key: 'Address', value: '1234 Somewhere Road • Nashville, TN 00000 • USA'}]`

2021-01-19 22:21 UTC, Arsen-Sultanov commented on components/ButtonG/index.js
> +    TouchableOpacity.button(style={width:width})
Можно сделать проще

2021-01-19 22:21 UTC, Arsen-Sultanov commented on components/ContentTitle/index.js
> +import {Text, View,  } from 'react-native'
Лишняя запятая

2021-01-19 22:21 UTC, Arsen-Sultanov commented on components/Section/index.js
> +import {Text, View,  } from 'react-native'
Лишняя запятая

2021-01-19 22:21 UTC, Arsen-Sultanov commented on components/ButtonG/index.js
> +import { observer } from 'startupjs'
зачем тебе observer?

2021-01-19 22:22 UTC, Arsen-Sultanov commented on components/ButtonG/index.js
> +export default observer(function ButtonG ({type='grey', text='Learn More', width='100%'}) {
https://github.com/KondrashovKonstantin/stellar/pull/2/files#r560535555

2021-01-19 22:43 UTC, Arsen-Sultanov commented on components/ContentTitle/index.js
> +import { observer } from 'startupjs'
https://github.com/KondrashovKonstantin/stellar/pull/2/files#r560535555

2021-01-19 22:43 UTC, Arsen-Sultanov commented on components/ContentTitle/index.js
> +export default observer(function ContentTitle ({title, align}) {
https://github.com/KondrashovKonstantin/stellar/pull/2/files#r560535555

2021-01-19 22:43 UTC, Arsen-Sultanov commented on components/ContentTitle/index.js
> +    console.log(align, title)
удали console.log

2021-01-19 22:43 UTC, Arsen-Sultanov commented on components/PlainText/index.js
> +import { observer } from 'startupjs'
https://github.com/KondrashovKonstantin/stellar/pull/2/files#r560535555

2021-01-19 22:43 UTC, Arsen-Sultanov commented on components/PlainText/index.js
> +export default observer(function PlainText ({text, size='small', align='center'}) {
https://github.com/KondrashovKonstantin/stellar/pull/2/files#r560535555

2021-01-19 22:43 UTC, Arsen-Sultanov commented on components/Section/index.js
> +import { observer } from 'startupjs'
https://github.com/KondrashovKonstantin/stellar/pull/2/files#r560535555

2021-01-19 22:43 UTC, Arsen-Sultanov commented on components/Section/index.js
> +export default observer(function Section ({Children}) {
https://github.com/KondrashovKonstantin/stellar/pull/2/files#r560535555

2021-01-19 22:43 UTC, Arsen-Sultanov commented on main/pages/PHome/Footer/index.js
> +import { observer } from 'startupjs'
https://github.com/KondrashovKonstantin/stellar/pull/2/files#r560535555

2021-01-19 22:43 UTC, Arsen-Sultanov commented on main/pages/PHome/MainContent/Statistic/index.js
> +
Можно проще

2021-01-19 22:43 UTC, Arsen-Sultanov commented on main/pages/PHome/MainContent/Statistic/index.js
> +            PlainText(text=text4, align='left')
![Снимок экрана 2021-01-20 в 1 35 15](https://user-images.githubusercontent.com/20321278/105102083-de507400-5abf-11eb-80f2-f783299bbb51.png)
![Снимок экрана 2021-01-20 в 1 37 42](https://user-images.githubusercontent.com/20321278/105102640-2374a600-5ac0-11eb-8dea-6fcf59d07be1.png)
text-align: justify

2021-01-19 22:43 UTC, Arsen-Sultanov commented on main/pages/PHome/MainContent/Cards/IconContent/index.js
> +import { PlainText } from '../../../../../../components'
`import { PlainText } from 'components'`

2021-01-19 22:43 UTC, Arsen-Sultanov commented on main/pages/PHome/MainContent/Cards/index.js
> +import { Section, ContentTitle, ButtonG } from '../../../../../components'
import { Section, ContentTitle, ButtonG } from 'components'

2021-01-19 22:43 UTC, Arsen-Sultanov commented on main/pages/PHome/MainContent/Cards/index.js
> +const bug = BASE_URL + 'debug.png'
Массив

2021-01-19 22:43 UTC, Arsen-Sultanov commented on main/pages/PHome/MainContent/Cards/index.js
> +                IconContent(text=text2, title = 'Dolor nullam', icon = bug)
https://pugjs.org/language/iteration.html

2021-01-19 22:43 UTC, Arsen-Sultanov commented on main/pages/PHome/MainContent/GetStarted/index.js
> +import { PlainText, Section, ContentTitle, ButtonG } from '../../../../../components'
import { PlainText, Section, ContentTitle, ButtonG } from 'components'

2021-01-19 22:43 UTC, Arsen-Sultanov commented on main/pages/PHome/MainContent/Intro/index.js
> +import { PlainText, Section, ContentTitle, ButtonG } from '../../../../../components'
import { PlainText, Section, ContentTitle, ButtonG } from 'components'

2021-01-19 22:54 UTC, Arsen-Sultanov commented on main/pages/PHome/Footer/index.js
> +                    Text.contacts-wrapper__element(styleName='detailed') information@untitled.tld
![Снимок экрана 2021-01-20 в 1 45 30](https://user-images.githubusercontent.com/20321278/105103270-5c614a80-5ac1-11eb-9a8d-afd2071d1bb3.png)
нет подчеркивания

2021-01-19 22:54 UTC, Arsen-Sultanov commented on main/pages/PHome/Footer/index.js
> +        Text.cprt © Untitled. Design: HTML5 UP. Demo Images: Unsplash.
у тебя в тексте должно быть две ссылки по макету

2021-01-19 22:54 UTC, Arsen-Sultanov commented on main/pages/PHome/MainContent/Cards/IconContent/index.styl
> +  padding 3px
Картинки расположены не поцентру добавь 
`justify-content center align-items center`
![Снимок экрана 2021-01-20 в 1 52 29](https://user-images.githubusercontent.com/20321278/105103772-31c3c180-5ac2-11eb-97fa-4a147bddec9a.png)
сделай картинки поменьше

2021-01-19 22:58 UTC, Arsen-Sultanov commented on main/pages/PHome/MainContent/CardHeader/index.js
> +            Text(styleName='header-item') Introduction
тут должна быть обводка
![Снимок экрана 2021-01-20 в 1 57 21](https://user-images.githubusercontent.com/20321278/105104204-dd6d1180-5ac2-11eb-8278-348ccde99627.png)

![Снимок экрана 2021-01-20 в 1 57 07](https://user-images.githubusercontent.com/20321278/105104289-0392b180-5ac3-11eb-9c60-d08ef9db95e1.png)

2021-01-20 10:07 UTC, lupenq requested changes

2021-01-20 10:07 UTC, lupenq commented on components/PlainText/index.styl
> +    font-size 1.7u
13,6px ?

2021-01-20 10:07 UTC, lupenq commented on components/ContentTitle/index.styl
> +.content-title
Давай будем давать название классам в виде camelCase

2021-01-20 10:07 UTC, lupenq commented on main/pages/PHome/MainContent/index.styl
> +  border-radius 0.5u
Вместо border-radius советую пользоваться миксином [radius()](https://startupjs-ui.dmapper.co/docs/foundation/BorderRadius)

2021-01-20 10:07 UTC, lupenq commented on components/Section/index.js
> +      Children
А что тут с чилдреном произошло? Правильно передавать чилдрен не через кастомный пропс, а вложив его в родительский компонент.

Там где ты используешь Section:
`  return pug`
    Section= StatisticContent
  ``

а здесь тогда 
`
function Section ({children})
`

и 
`
return pug`  
    View.holder.section
      = сhildren
`

2021-01-20 10:07 UTC, lupenq commented on components/Section/index.js
> +      Children
https://ru.reactjs.org/docs/composition-vs-inheritance.html

2021-01-20 10:07 UTC, lupenq commented on components/ButtonG/index.js
> +      Text.button__text(styleName='dark') #{text}
Text.button__text(styleName='dark')= text

Такая запись корректней

2021-01-20 10:07 UTC, lupenq commented on components/ButtonG/index.styl
> +    border 0.125u solid #dddddd
border 1px solid #dddddd

2021-01-20 10:07 UTC, lupenq commented on components/ButtonG/index.styl
> +    border-radius 1u
radius(l)

2021-01-20 10:07 UTC, lupenq commented on components/ButtonG/index.styl
> +    height: 5u
':' нужно убрать везде

2021-01-20 10:07 UTC, lupenq commented on components/ButtonG/index.styl
> +        max-width 30u
Еще общий комментарий: установи у себя в редакторе размер отступов в 2 пробела.
Если это vscode:

    "editor.tabSize": 2,
в settings.json

2021-01-20 10:07 UTC, lupenq commented on components/ButtonG/index.styl
> +        font-size 1.8u
14.4px?

2021-01-20 10:07 UTC, lupenq commented on components/ContentTitle/index.styl
> +$dark = rgb(99, 99, 99)
локальные переменные в stylus объявляй через _, _dark = ....

2021-01-20 10:07 UTC, lupenq commented on components/PlainText/index.styl
> +        font-size 2.8u
22.4px? Давай использовать дробные юнита только в крайнем случае, и то только с шагом в 0.5, здесь легко можно указать 3u

2021-01-20 10:07 UTC, lupenq commented on components/PlainText/index.styl
> +        text-align left
Странно выглядит. Название класса .left, а он центрирует текст, но на декстопе влево его уводит

2021-01-20 10:07 UTC, lupenq commented on main/pages/PHome/Footer/index.styl
> +        display flex
display flex лишнее, в реакт нейтиве он стоит по умолчанию у каждого элемента

2021-01-20 10:07 UTC, lupenq commented on main/pages/PHome/Header/index.styl
> +  margin: 3u 0 0 0
margin-top

2021-01-20 10:07 UTC, lupenq commented on main/pages/PHome/Header/index.styl
> +  border-radius 11u
radius(circle)

2021-01-20 10:07 UTC, lupenq commented on main/pages/PHome/MainContent/CardHeader/index.js
> +            Text(styleName='header-item') Introduction
Text.headerItem Introduction

2021-01-20 10:07 UTC, lupenq commented on main/pages/PHome/MainContent/Cards/IconContent/index.styl
> +    padding 7px
1u

2021-01-20 10:07 UTC, lupenq commented on main/pages/PHome/MainContent/Cards/IconContent/index.styl
> +    padding 15px
2u

2021-01-20 10:07 UTC, lupenq commented on main/pages/PHome/MainContent/Cards/IconContent/index.styl
> +  position relative
Лишнее, каждый элемент по умолчанию position relative

2021-01-20 10:07 UTC, lupenq commented on main/pages/PHome/MainContent/GetStarted/index.styl
> +.first
```
.btn-wrapper
 &.first
   margin 0
```

2021-01-20 10:07 UTC, lupenq commented on main/pages/PHome/MainContent/Intro/index.js
> +                ButtonG
а почему именно ButtonG? Что значит G?

2021-01-20 10:07 UTC, lupenq commented on main/pages/PHome/MainContent/Statistic/StatCard/index.js
> +        key=val.uri,
отступы

2021-01-20 10:07 UTC, lupenq commented on main/pages/PHome/MainContent/Statistic/StatCard/index.js
> +        styleName=index===0?'first': index===items.length-1?'last':null)
styleName={ first: !index, last: index === items.length - 1 }
Вот такая запись корректней

2021-01-20 10:07 UTC, lupenq commented
Почитай эту [ссылочку](https://startupjs-ui.dmapper.co/docs/tutorial/Basics#%D0%94%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%20%D1%81%D1%82%D0%B8%D0%BB%D0%B8) касательно styleName

2021-01-20 11:53 UTC, lupenq requested changes

2021-01-20 11:53 UTC, lupenq commented on main/pages/PHome/index.styl
> +  font-family Ubuntu Thin
Не задавай свои font-family, используй стандартный

2021-01-20 11:55 UTC, lupenq commented
Пройдись еще глазами по оригиналу и своей верстке, и сверь размеры, отступы, шрифты и прочее. Очень большие отличия от оригинал есть

2021-01-20 13:40 UTC, KondrashovKonstantin commented on components/ButtonG/index.js
> +      Text.button__text(styleName='dark') #{text}
done

2021-01-20 13:43 UTC, KondrashovKonstantin commented on components/ButtonG/index.styl
> +    height: 5u
done

2021-01-20 13:45 UTC, KondrashovKonstantin commented on components/ButtonG/index.styl
> +    border 0.125u solid #dddddd
done

2021-01-20 13:56 UTC, KondrashovKonstantin commented on components/ButtonG/index.styl
> +    border-radius 1u
done

2021-01-20 13:57 UTC, KondrashovKonstantin commented on components/ButtonG/index.styl
> +        font-size 1.8u
done

2021-01-20 13:58 UTC, KondrashovKonstantin commented on components/ContentTitle/index.js
> +import {Text, View,  } from 'react-native'
done

2021-01-20 13:58 UTC, KondrashovKonstantin commented on components/ContentTitle/index.js
> +    console.log(align, title)
done

2021-01-20 14:02 UTC, KondrashovKonstantin commented on components/ContentTitle/index.styl
> +$dark = rgb(99, 99, 99)
done

2021-01-20 14:03 UTC, KondrashovKonstantin commented on components/ContentTitle/index.styl
> +.content-title
done

2021-01-20 14:04 UTC, KondrashovKonstantin commented on components/PlainText/index.styl
> +    font-size 1.7u
done

2021-01-20 14:04 UTC, KondrashovKonstantin commented on components/PlainText/index.styl
> +        font-size 2.8u
done

2021-01-20 14:06 UTC, KondrashovKonstantin commented on components/Section/index.js
> +import {Text, View,  } from 'react-native'
done

2021-01-20 14:06 UTC, KondrashovKonstantin commented on main/pages/PHome/Footer/index.js
> +import { ButtonG } from '../../../../components'
done

2021-01-20 14:07 UTC, KondrashovKonstantin commented on main/pages/PHome/Footer/index.js
> +const BASE_URL = 'http://localhost:3010/public/'
Не работает на версии StartupJS с которой был заиничен проэки

2021-01-20 14:08 UTC, lupenq commented on main/pages/PHome/Footer/index.js
> +const BASE_URL = 'http://localhost:3010/public/'
Как это? Покажи

2021-01-20 14:11 UTC, KondrashovKonstantin commented on main/pages/PHome/Footer/index.styl
> +        display flex
done

2021-01-20 14:11 UTC, KondrashovKonstantin commented on main/pages/PHome/Header/index.styl
> +  border-radius 11u
done

2021-01-20 14:12 UTC, KondrashovKonstantin commented on main/pages/PHome/Header/index.styl
> +  margin: 3u 0 0 0
done

2021-01-20 14:14 UTC, KondrashovKonstantin commented on main/pages/PHome/MainContent/CardHeader/index.js
> +            Text(styleName='header-item') Introduction
done

2021-01-20 14:15 UTC, KondrashovKonstantin commented on main/pages/PHome/MainContent/Cards/IconContent/index.js
> +import { PlainText } from '../../../../../../components'
done

2021-01-20 14:17 UTC, KondrashovKonstantin commented on main/pages/PHome/MainContent/Cards/IconContent/index.styl
> +  padding 3px
done

2021-01-20 14:18 UTC, KondrashovKonstantin commented on main/pages/PHome/MainContent/Cards/IconContent/index.styl
> +    padding 7px
done

2021-01-20 14:18 UTC, KondrashovKonstantin commented on main/pages/PHome/MainContent/Cards/IconContent/index.styl
> +    padding 15px
done

2021-01-20 14:19 UTC, KondrashovKonstantin commented on main/pages/PHome/MainContent/Cards/IconContent/index.styl
> +  position relative
done

2021-01-20 14:19 UTC, KondrashovKonstantin commented on main/pages/PHome/MainContent/Cards/index.js
> +import { Section, ContentTitle, ButtonG } from '../../../../../components'
done

2021-01-20 14:19 UTC, KondrashovKonstantin commented on main/pages/PHome/MainContent/GetStarted/index.js
> +import { PlainText, Section, ContentTitle, ButtonG } from '../../../../../components'
done

2021-01-20 14:20 UTC, KondrashovKonstantin commented on main/pages/PHome/MainContent/GetStarted/index.styl
> +.first
done

2021-01-20 14:20 UTC, KondrashovKonstantin commented on main/pages/PHome/MainContent/Intro/index.js
> +import { PlainText, Section, ContentTitle, ButtonG } from '../../../../../components'
done

2021-01-20 14:21 UTC, KondrashovKonstantin commented on main/pages/PHome/MainContent/Intro/index.js
> +                ButtonG
Done (Если бы я помнил что оно значит)

2021-01-20 14:22 UTC, KondrashovKonstantin commented on main/pages/PHome/MainContent/Statistic/StatCard/index.js
> +        key=val.uri,
done

2021-01-20 14:38 UTC, KondrashovKonstantin commented on main/pages/PHome/MainContent/Statistic/StatCard/index.js
> +        styleName=index===0?'first': index===items.length-1?'last':null)
done

2021-01-20 14:41 UTC, KondrashovKonstantin commented on main/pages/PHome/MainContent/index.styl
> +  border-radius 0.5u
done

2021-01-20 14:44 UTC, KondrashovKonstantin commented on main/pages/PHome/index.styl
> +  font-family Ubuntu Thin
done

2021-01-20 15:02 UTC, KondrashovKonstantin commented on main/pages/PHome/Footer/index.styl
> +        margin-left 2u
done

2021-01-20 15:05 UTC, KondrashovKonstantin commented on main/pages/PHome/Footer/index.js
> +        Text.cprt © Untitled. Design: HTML5 UP. Demo Images: Unsplash.
done

2021-01-20 15:18 UTC, KondrashovKonstantin commented on components/Section/index.js
> +      Children
done

2021-01-20 16:08 UTC, KondrashovKonstantin commented on main/pages/PHome/Footer/index.js
> +const BASE_URL = 'http://localhost:3010/public/'
При импорте BASE_URL из "@env"

![image](https://user-images.githubusercontent.com/43877974/105202171-5cf1f380-5b4a-11eb-81a4-0499679a5a98.png)

2021-01-20 16:09 UTC, KondrashovKonstantin commented on main/pages/PHome/Footer/index.js
> +const BASE_URL = 'http://localhost:3010/public/'
При замене на 3010 порт руками - все работает

2021-01-21 08:37 UTC, lupenq commented
Смотри как футер вылезает за границы контента по бокам

![image](https://user-images.githubusercontent.com/25533519/105324863-0386d480-5bdd-11eb-87e6-3b2c90aab582.png)

2021-01-21 08:39 UTC, lupenq commented
Необходимо задать максимальную ширину всей странице, чтобы на большом разрешении экрана весь контент не расширялся до бесконечности

![image](https://user-images.githubusercontent.com/25533519/105325031-303aec00-5bdd-11eb-9850-03cc094361b0.png)

2021-01-21 09:38 UTC, lupenq requested changes

2021-01-21 09:38 UTC, lupenq commented on components/Button/index.js
> +import {Text, TouchableOpacity,  } from 'react-native'
запятая

2021-01-21 09:38 UTC, lupenq commented on components/Button/index.js
> +        Text.buttonText=text
Давай похожим образом упростим этот компонент. Только модификаторы(.dark, .blue) указывай через амперсанд в styl.

![image](https://user-images.githubusercontent.com/25533519/105325758-02a27280-5bde-11eb-907d-8bc2e2ff33f6.png)

2021-01-21 09:38 UTC, lupenq commented on components/Button/index.styl
> +    height: 5u
Установи себе https://marketplace.visualstudio.com/items?itemName=sysoev.language-stylus и в его настройках сними галочку, чтобы двоеточия сами не ставились
![image](https://user-images.githubusercontent.com/25533519/105326131-76dd1600-5bde-11eb-8b1a-5b358798d433.png)

2021-01-21 09:38 UTC, lupenq commented on components/PlainText/index.js
> +        Text.bigtext(styleName='plaintext #{align}')=text
Text.bigtext(styleName=['plaintext', align)= text

2021-01-21 09:38 UTC, lupenq commented on components/PlainText/index.styl
> +        line-height 5.6u
44.8px?

Я уже оставлял комментарий по поводу дробных пикселей. Их мы используем только в крайних случаях. Пройдись по всему коду внимательно

2021-01-21 09:38 UTC, lupenq commented on components/PlainText/index.styl
> +        text-align left
ping

2021-01-21 09:38 UTC, lupenq commented on components/PlainText/index.styl
> +    text-align center
а тут класс justify, а он центрирует

2021-01-21 09:38 UTC, lupenq commented on components/Section/index.js
> +    View.root.section= children
зачем тебе класс section? Указывай его стили в .root

2021-01-21 09:38 UTC, lupenq commented on main/Layout/index.styl
> +  height _menuHeight
размеры не обязательно выносить в переменные

2021-01-21 09:38 UTC, lupenq commented on main/Layout/index.js
> +import { Row, Div} from '@startupjs/ui'
удали неиспользуемые переменные

2021-01-21 09:38 UTC, lupenq commented on main/Layout/index.js
> +import { Row, Div} from '@startupjs/ui'
и в целом следи за чистотой кода. неиспользуемые переменные, лишние пробелы, лишние отступы строк

2021-01-21 09:38 UTC, lupenq commented on main/Layout/index.js
> +    Div.body= children
.root

2021-01-21 09:38 UTC, lupenq commented on main/Layout/index.styl
>  .menu
У тебя нет всех этих классов в index.js, кроме .body. удали лишнее

2021-01-21 09:38 UTC, lupenq commented on main/pages/PHome/Footer/index.js
> +            Text(styleName='text') #{text}
Text.text= text

2021-01-21 09:38 UTC, lupenq commented on main/pages/PHome/Footer/index.js
> +                            style=item.key==='Email'?{textDecorationLine:'underline'}:null)= item.value
давай стараться не использовать style, а все стили держать в .styl

2021-01-21 09:38 UTC, lupenq commented on main/pages/PHome/Footer/index.styl
> +_white_transp = rgba(255, 255, 255, 0.35)
camelCase для переменных

2021-01-21 09:38 UTC, lupenq commented on main/pages/PHome/Footer/index.styl
> +        padding 15u 15u
padding 15u

2021-01-21 09:38 UTC, lupenq commented on main/pages/PHome/Footer/index.styl
> +        font-size 2.2u
font-size 2u

2021-01-21 09:38 UTC, lupenq commented on main/pages/PHome/Footer/index.styl
> +        font-size 2.2u
same

2021-01-21 09:38 UTC, lupenq commented on main/pages/PHome/MainContent/CardHeader/index.js
> +    `
Давай тут each заюзаем.

![image](https://user-images.githubusercontent.com/25533519/105331054-1224ba00-5be4-11eb-9458-f45f9162d561.png)

2021-01-21 09:38 UTC, lupenq commented on main/pages/PHome/MainContent/CardHeader/index.styl
> +    font-size 2.4u
same

2021-01-21 09:38 UTC, lupenq commented on main/pages/PHome/MainContent/Cards/IconContent/index.js
> +      View.iconHolder(styleName='innerHolder')
думаю на 11 и 12 строчке одного View будет достаточно

2021-01-21 09:38 UTC, lupenq commented on main/pages/PHome/MainContent/Cards/index.js
> +          for item in imgs
давай each вместо for

2021-01-21 09:38 UTC, lupenq commented on main/pages/PHome/MainContent/Statistic/StatCard/index.js
> +        style={backgroundColor: val.color},
нет, отсупы тут по другому выглядят и запятые не нужны в пропсах

![image](https://user-images.githubusercontent.com/25533519/105331700-cfafad00-5be4-11eb-8d96-db19349f9bfc.png)

2021-01-21 09:38 UTC, lupenq commented on main/pages/PHome/MainContent/Statistic/StatCard/index.styl
> +.last
.first и .last под .stat через амперсанд размести

2021-01-21 09:38 UTC, lupenq commented on main/pages/PHome/MainContent/Statistic/index.js
> +    Section= StatisticContent
А почему не сделать сразу так?

![image](https://user-images.githubusercontent.com/25533519/105332132-52386c80-5be5-11eb-88a9-d533406a366a.png)

2021-01-21 09:38 UTC, lupenq commented on main/pages/PHome/index.styl
> +  font-weight 100
лишнее

2021-01-21 14:47 UTC, KondrashovKonstantin commented on components/Button/index.js
> +import {Text, TouchableOpacity,  } from 'react-native'
done

2021-01-21 15:13 UTC, KondrashovKonstantin commented on components/PlainText/index.styl
> +        text-align left
Там по дизайну текст начиная с десктопа в лево уводить должно, а модификатор нужен потому что этот компонент реюзается и в остальных случаях он отцентрован должен быть

2021-01-21 15:14 UTC, KondrashovKonstantin commented on components/PlainText/index.styl
> +    text-align center
То же самое что и с left. 
Отрефакторил и добавли в styl их через .&

2021-01-22 08:16 UTC, lupenq requested changes

2021-01-22 08:16 UTC, lupenq commented on .vscode/settings.json
> +    "languageStylus.useSeparator": false
Следи чтобы такие папки\файлы не попадали в коммит.
https://andrew-r.ru/notes/2020-01-14-global-gitignore/ вот подсказка

2021-01-22 08:16 UTC, lupenq commented on components/Button/index.js
> +
Две лишние строки

2021-01-22 08:16 UTC, lupenq commented on components/ContentTitle/index.js
> +
same

2021-01-22 08:16 UTC, lupenq commented on components/ContentTitle/index.styl
> +
Тоже самое в стилях.
Здесь минус строка

2021-01-22 08:16 UTC, lupenq commented on components/ContentTitle/index.styl
> +.contentTitleText
Здесь плюс строка

2021-01-22 08:16 UTC, lupenq commented on components/ContentTitle/index.styl
> +
Здесь минус

2021-01-22 08:16 UTC, lupenq commented on components/ContentTitle/index.styl
> +
Это не просто придирка, так намного повышается читаемость и на реальных проектах это будет мастхев

2021-01-22 08:16 UTC, lupenq commented on components/PlainText/index.js
> +import {Text, View,  } from 'react-native'
запятая

2021-01-22 08:16 UTC, lupenq commented on components/PlainText/index.styl
> +    font-size 13px
1.5u для шрифтов можно указывать

2021-01-22 08:16 UTC, lupenq commented on components/PlainText/index.styl
> +        font-size 20px
2.5u

2021-01-22 08:16 UTC, lupenq commented on components/PlainText/index.styl
> +            font-size 16px
2u

2021-01-22 08:16 UTC, lupenq commented on components/Section/index.js
> +  console.log(isLast)
log

2021-01-24 15:37 UTC, Arsen-Sultanov commented on main/pages/PHome/Footer/index.js
> +const BASE_URL = 'http://localhost:3010/public/'
import { BASE_URL } from '@env' // http://127.0.0.1:3000
const PUBLIC_FOLDER = BASE_URL + '/public/'

2021-09-06 20:15 UTC, merged